<a href="https://colab.research.google.com/github/saheedadey/Quiz-answer/blob/master/Hackathon1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Team Global Green
###> We are working on "Preventing The Amplification of Fake News on Climate Change"

The Datasets: We use two publicly available datasets,
namely PolitiFact political claims, climate and health data generated from different websites (Popat et al, 2018)

In [11]:
import pandas as pd

In [12]:
#Lets dowload the dataset
url = 'https://github.com/rahulOmishra/SUMO/raw/main/climate_claims_raw.xlsx'
df = pd.read_excel(url)
df

     climate_claim  ... Unnamed: 4
0         Claim_id  ...      Label
1                0  ...      False
2                0  ...      False
3                0  ...      False
4                0  ...      False
...            ...  ...        ...
1032           105  ...      False
1033           105  ...      False
1034           105  ...      False
1035           105  ...      False
1036           105  ...      False

[1037 rows x 5 columns]

In [13]:
df1 = pd.DataFrame(df)
df1

     climate_claim  ... Unnamed: 4
0         Claim_id  ...      Label
1                0  ...      False
2                0  ...      False
3                0  ...      False
4                0  ...      False
...            ...  ...        ...
1032           105  ...      False
1033           105  ...      False
1034           105  ...      False
1035           105  ...      False
1036           105  ...      False

[1037 rows x 5 columns]

In [14]:
# Checking the Dataset column
df.head(1)

  climate_claim Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0      Claim_id      Claim      Title   Doc_text      Label

In [15]:
# Since many of the Column are Unnamed, we try to rename them appropriately

replace = {'climate_claim': 'ID', 'Unnamed: 1':"Claim", 'Unnamed: 2':'Title', 'Unnamed: 3':'Story', 'Unnamed: 4':'Label' }

In [16]:
df1.rename(columns=replace, inplace=True)
df

            ID  ...  Label
0     Claim_id  ...  Label
1            0  ...  False
2            0  ...  False
3            0  ...  False
4            0  ...  False
...        ...  ...    ...
1032       105  ...  False
1033       105  ...  False
1034       105  ...  False
1035       105  ...  False
1036       105  ...  False

[1037 rows x 5 columns]

In [17]:
# Droping the fisrt row because it doesn't useful
df1.drop(index=df.index[0], axis = 0)

       ID  ...  Label
1       0  ...  False
2       0  ...  False
3       0  ...  False
4       0  ...  False
5       0  ...  False
...   ...  ...    ...
1032  105  ...  False
1033  105  ...  False
1034  105  ...  False
1035  105  ...  False
1036  105  ...  False

[1036 rows x 5 columns]

In [21]:
df1.drop(['ID', 'Title', 'Story'], axis = 1, inplace=True)

In [22]:
df1

                                                  Claim  Label
0                                                 Claim  Label
1     The drop in NO2 content has only been ?slight?...  False
2     The drop in NO2 content has only been ?slight?...  False
3     The drop in NO2 content has only been ?slight?...  False
4     The drop in NO2 content has only been ?slight?...  False
...                                                 ...    ...
1032               Smoking may protect against COVID-19  False
1033               Smoking may protect against COVID-19  False
1034               Smoking may protect against COVID-19  False
1035               Smoking may protect against COVID-19  False
1036               Smoking may protect against COVID-19  False

[1037 rows x 2 columns]

### Let's try to Tokenize the dataset to be able to generate embedling